<?php

namespace Tests\Feature\Rcsa;

use App\Models\Rcsa\RcsaAssessment;
use App\Models\Rcsa\RcsaImportBatch;
use App\Services\Rcsa\RcsaAssessmentService;
use App\Services\Rcsa\RcsaCycleService;
use App\Services\Rcsa\RcsaRoundTripService;
use App\Services\Rcsa\RcsaWorkbookWriter;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use PhpOffice\PhpSpreadsheet\IOFactory;
use Inertia\Testing\AssertableInertia;
use PHPUnit\Framework\Attributes\Test;

/**
 * §10.4 — the offline round trip.
 *
 * EVERY TEST HERE GOES THROUGH THE REAL FILE. The working copy is generated by
 * the writer, opened with PhpSpreadsheet, edited the way a branch manager would
 * edit it, and uploaded back. P2's lesson was that a workbook the product
 * produced was rejected by its own importer, and only a round trip finds that.
 */
class RoundTripTest extends CycleTestCase
{
    private RcsaAssessment $assessment;

    protected function setUp(): void
    {
        parent::setUp();

        Storage::fake('local');

        foreach (range(1, 3) as $i) {
            $this->publishedRisk(['risk_no' => "RETAIL-R{$i}"]);
        }

        $cycle = $this->makeCycle();
        app(RcsaCycleService::class)->open($cycle, $this->actor);

        $this->assessment = RcsaAssessment::query()->where('business_unit_id', $this->retail->id)->sole();

        $service = app(RcsaAssessmentService::class);

        foreach ($this->assessment->lines()->get() as $line) {
            $service->apply($line, [
                'inherent_likelihood' => 2,
                'inherent_impact' => 2,
                'control_effectiveness' => 'Mostly Achieved',
            ], $this->actor);
        }
    }

    /**
     * Download the working copy the way the user does, and hand back the path
     * of the file on disk.
     */
    private function downloadWorkingCopy(): string
    {
        $response = $this->actingAs($this->actor)
            ->get(route('rcsa.round-trip.working-copy', $this->assessment));

        $response->assertOk();

        $path = tempnam(sys_get_temp_dir(), 'wc').'.xlsx';
        file_put_contents($path, $response->streamedContent());

        return $path;
    }

    /**
     * Edit cells by their HEADER LABEL, as a person would — not by column
     * index, which would make the test pass even if the columns moved.
     *
     * @param  array<int, array<string, mixed>>  $edits  1-based data row => label => value
     */
    private function edit(string $path, array $edits): string
    {
        $spreadsheet = IOFactory::load($path);
        $sheet = $spreadsheet->getSheetByName(RcsaWorkbookWriter::SHEET_RCSA);

        $header = [];

        foreach ($sheet->getRowIterator(1, 1) as $row) {
            foreach ($row->getCellIterator() as $cell) {
                $header[(string) $cell->getValue()] = $cell->getColumn();
            }
        }

        foreach ($edits as $dataRow => $cells) {
            foreach ($cells as $label => $value) {
                $this->assertArrayHasKey($label, $header, "The working copy has no column called \"{$label}\".");
                $sheet->setCellValue($header[$label].($dataRow + 1), $value);
            }
        }

        $out = tempnam(sys_get_temp_dir(), 'wc-edited').'.xlsx';
        (new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet))->save($out);

        return $out;
    }

    /**
     * The conflict screen itself — GET, not just the actions on it.
     *
     * The parity guard caught this: every other round-trip route had a test
     * naming it, and `show` had none. The screen that renders the comparison a
     * user actually reads had never been requested by anything but a person,
     * which is precisely the gap the guard exists to report.
     */
    #[Test]
    public function the_batch_screen_renders_the_rows_it_will_apply(): void
    {
        $batch = $this->upload($this->downloadWorkingCopy());

        $this->actingAs($this->actor)
            ->get(route('rcsa.round-trip.show', [$this->assessment, $batch]))
            ->assertOk()
            ->assertInertia(fn (AssertableInertia $page) => $page
                ->component('RcsaRoundTrip/Show')
                ->where('batch.id', $batch->id)
                ->where('assessment.id', $this->assessment->id)
                ->has('rows')
            );
    }

    private function upload(string $path): RcsaImportBatch
    {
        $this->actingAs($this->actor)
            ->post(route('rcsa.round-trip.store', $this->assessment), [
                'file' => new UploadedFile($path, 'working-copy.xlsx', null, null, true),
            ])
            ->assertRedirect();

        return RcsaImportBatch::query()->latest('id')->firstOrFail();
    }

    /* ------------------------------------------------------------------ */
    /*  The file the product produces */
    /* ------------------------------------------------------------------ */

    #[Test]
    public function the_working_copy_carries_the_hidden_identity_columns(): void
    {
        $path = $this->downloadWorkingCopy();

        $rows = app(\App\Services\SpreadsheetReader::class)->rows($path, RcsaWorkbookWriter::SHEET_RCSA);

        // One header row, then the data — the group banner belongs on the
        // export a regulator reads, not on a form somebody fills in.
        $this->assertSame('__line_id', $rows[0][0]);
        $this->assertSame('__version', $rows[0][1]);
        $this->assertSame('Risk No.', $rows[0][2]);

        $ids = $this->assessment->lines()->pluck('id')->all();

        $this->assertEqualsCanonicalizing(
            $ids,
            array_map(fn ($row) => (int) $row[0], array_slice($rows, 1)),
        );
    }

    /* ------------------------------------------------------------------ */
    /*  The three rules */
    /* ------------------------------------------------------------------ */

    #[Test]
    public function edits_made_offline_come_back_and_are_recomputed_here(): void
    {
        $edited = $this->edit($this->downloadWorkingCopy(), [
            1 => ['Likelihood (without control)' => 5, 'Impact (without control)' => 5, 'Control Effectiveness' => 'Not Achieved'],
        ]);

        $batch = $this->upload($edited);

        $line = $this->assessment->lines()->first();

        // NOTHING WRITTEN YET. Stage, preview, confirm.
        $this->assertSame(2, (int) $line->fresh()->inherent_likelihood);

        $this->actingAs($this->actor)
            ->post(route('rcsa.round-trip.apply', [$this->assessment, $batch]))
            ->assertRedirect(route('rcsa.assessments.show', $this->assessment));

        $line->refresh();

        $this->assertSame(5, (int) $line->inherent_likelihood);
        $this->assertSame('Not Achieved', $line->control_effectiveness);
        // Recomputed HERE, by the engine — the file's own numbers were never
        // read.
        $this->assertSame(25, (int) $line->inherent_score);
        $this->assertSame('very_high', $line->residual_level);
    }

    /**
     * The greyed columns are a courtesy; this is the enforcement.
     */
    #[Test]
    public function a_calculated_column_typed_over_in_excel_is_discarded(): void
    {
        $edited = $this->edit($this->downloadWorkingCopy(), [
            1 => [
                'Likelihood (without control)' => 3,
                // Everything a spreadsheet should not be able to say.
                'Residual Risk' => 999,
                'Risk Score' => 999,
                'Inherent Risk Level' => 'very_low',
                'Business Unit' => 'Treasury',
                'Potential Risk' => 'A risk statement rewritten in Excel.',
            ],
        ]);

        $batch = $this->upload($edited);

        $this->actingAs($this->actor)->post(route('rcsa.round-trip.apply', [$this->assessment, $batch]));

        $line = $this->assessment->lines()->first()->fresh();

        // The one thing it was allowed to change.
        $this->assertSame(3, (int) $line->inherent_likelihood);

        // And none of the rest.
        $this->assertNotSame(999.0, (float) $line->residual_score);
        $this->assertSame(6, (int) $line->inherent_score);
        $this->assertSame($this->retail->name, $line->business_unit_name);
        $this->assertStringNotContainsString('rewritten in Excel', (string) $line->potential_risk);
    }

    /**
     * THE RULE THE WHOLE FEATURE RESTS ON.
     */
    #[Test]
    public function a_line_somebody_else_changed_is_flagged_rather_than_overwritten(): void
    {
        $path = $this->downloadWorkingCopy();

        $lines = $this->assessment->lines()->get();
        $contested = $lines->first();
        $quiet = $lines->last();

        // Somebody else answers the same risk while the file is on a laptop.
        app(RcsaAssessmentService::class)->apply(
            $contested,
            ['inherent_likelihood' => 4, 'control_effectiveness' => 'Partially Achieved'],
            $this->reviewerUser(),
        );

        $edited = $this->edit($path, [
            1 => ['Likelihood (without control)' => 1],
            3 => ['Likelihood (without control)' => 5],
        ]);

        $batch = $this->upload($edited);

        $rows = collect(app(RcsaRoundTripService::class)->preview($batch));

        $conflict = $rows->firstWhere('line_id', $contested->id);
        $clean = $rows->firstWhere('line_id', $quiet->id);

        $this->assertTrue($conflict['is_conflict']);
        // DEFAULTS TO KEEPING WHAT IS IN THE SYSTEM. The colleague's morning is
        // not lost to a fortnight-old file by default.
        $this->assertSame(RcsaRoundTripService::ACTION_THEIRS, $conflict['action']);
        $this->assertSame(4, $conflict['theirs']['inherent_likelihood']);
        $this->assertSame(1, $conflict['changes']['inherent_likelihood']);

        $this->assertFalse($clean['is_conflict']);
        $this->assertSame(RcsaRoundTripService::ACTION_MINE, $clean['action']);

        // Applying now leaves the contested line alone and writes the other.
        $this->actingAs($this->actor)->post(route('rcsa.round-trip.apply', [$this->assessment, $batch]));

        $this->assertSame(4, (int) $contested->fresh()->inherent_likelihood);
        $this->assertSame(5, (int) $quiet->fresh()->inherent_likelihood);
    }

    #[Test]
    public function the_user_can_choose_their_own_answer_on_a_conflict(): void
    {
        $path = $this->downloadWorkingCopy();

        $contested = $this->assessment->lines()->first();

        app(RcsaAssessmentService::class)->apply(
            $contested,
            ['inherent_likelihood' => 4],
            $this->reviewerUser(),
        );

        $batch = $this->upload($this->edit($path, [1 => ['Likelihood (without control)' => 1]]));

        $row = collect(app(RcsaRoundTripService::class)->preview($batch))->firstWhere('line_id', $contested->id);

        $this->actingAs($this->actor)
            ->post(route('rcsa.round-trip.resolve', [$this->assessment, $batch, $row['id']]), [
                'action' => RcsaRoundTripService::ACTION_MINE,
            ])
            ->assertRedirect();

        $this->actingAs($this->actor)->post(route('rcsa.round-trip.apply', [$this->assessment, $batch]));

        $this->assertSame(1, (int) $contested->fresh()->inherent_likelihood);
    }

    /* ------------------------------------------------------------------ */
    /*  Bad files */
    /* ------------------------------------------------------------------ */

    #[Test]
    public function a_value_outside_the_methodologys_scale_is_an_error_not_a_conflict(): void
    {
        $batch = $this->upload($this->edit($this->downloadWorkingCopy(), [
            1 => ['Control Effectiveness' => 'Brilliantly Achieved'],
        ]));

        $row = collect(app(RcsaRoundTripService::class)->preview($batch))->first();

        $this->assertSame('error', $row['status']);
        $this->assertFalse($row['is_conflict']);
        $this->assertSame('not_in_scale', $row['errors'][0]['rule']);

        // And it cannot be resolved into an apply — a value the engine cannot
        // score is not a disagreement between two people.
        $this->actingAs($this->actor)
            ->post(route('rcsa.round-trip.resolve', [$this->assessment, $batch, $row['id']]), [
                'action' => RcsaRoundTripService::ACTION_MINE,
            ])
            ->assertSessionHas('error');
    }

    #[Test]
    public function a_row_for_a_risk_that_is_not_in_this_assessment_is_refused(): void
    {
        $path = $this->downloadWorkingCopy();

        $edited = $this->edit($path, [1 => ['__line_id' => 999999]]);

        $batch = $this->upload($edited);

        $row = collect(app(RcsaRoundTripService::class)->preview($batch))->first();

        $this->assertSame('error', $row['status']);
        $this->assertSame('unknown_line', $row['errors'][0]['rule']);
    }

    /**
     * The universe template has no line ids, and uploading one here would
     * otherwise match nothing and silently report five unchanged rows.
     */
    #[Test]
    public function a_file_with_no_identity_columns_is_rejected_with_an_explanation(): void
    {
        $template = app(\App\Services\Rcsa\RcsaTemplateWriter::class)->universeTemplate($this->organization->id);

        $path = tempnam(sys_get_temp_dir(), 'universe').'.xlsx';
        file_put_contents($path, $template);

        $response = $this->actingAs($this->actor)
            ->post(route('rcsa.round-trip.store', $this->assessment), [
                'file' => new UploadedFile($path, 'universe.xlsx', null, null, true),
            ]);

        $response->assertSessionHas('error');
        $this->assertStringContainsString('no risk identifiers', session('error'));
    }

    /* ------------------------------------------------------------------ */
    /*  P5's rule holds here too */
    /* ------------------------------------------------------------------ */

    /**
     * And the screen says so BEFORE the user chooses, not after apply refuses
     * it. Found by driving the page: the preview offered a Mine/System toggle
     * on a row the server was always going to reject.
     */
    #[Test]
    public function a_locked_line_is_marked_on_the_preview_and_cannot_be_resolved(): void
    {
        $path = $this->downloadWorkingCopy();

        $lines = $this->assessment->lines()->get();
        $lines->skip(1)->each(fn ($line) => $line->forceFill(['locked_at' => now()])->save());

        $batch = $this->upload($this->edit($path, [
            1 => ['Likelihood (without control)' => 5],
            2 => ['Likelihood (without control)' => 5],
        ]));

        $rows = collect(app(RcsaRoundTripService::class)->preview($batch));

        $open = $rows->firstWhere('line_id', $lines->first()->id);
        $locked = $rows->firstWhere('line_id', $lines->get(1)->id);

        $this->assertFalse($open['is_locked']);
        $this->assertTrue($locked['is_locked']);
        $this->assertSame(RcsaRoundTripService::ACTION_THEIRS, $locked['action']);

        // And choosing "mine" on it is refused here rather than silently
        // deferred to apply.
        $this->actingAs($this->actor)
            ->post(route('rcsa.round-trip.resolve', [$this->assessment, $batch, $locked['id']]), [
                'action' => RcsaRoundTripService::ACTION_MINE,
            ])
            ->assertSessionHas('error');
    }

    #[Test]
    public function an_offline_file_cannot_reopen_a_line_the_orm_left_locked(): void
    {
        $path = $this->downloadWorkingCopy();

        // Lock every line, as submission does.
        $this->assessment->lines()->update(['locked_at' => now()]);
        $this->assessment->forceFill(['status' => RcsaAssessment::RETURNED])->save();

        // Reopen exactly one, as a return does.
        $reopened = $this->assessment->lines()->first();
        $reopened->forceFill(['locked_at' => null])->save();

        $edited = $this->edit($path, [
            1 => ['Likelihood (without control)' => 5],
            2 => ['Likelihood (without control)' => 5],
        ]);

        $batch = $this->upload($edited);

        $this->actingAs($this->actor)
            ->post(route('rcsa.round-trip.apply', [$this->assessment, $batch]))
            ->assertRedirect();

        $lines = $this->assessment->lines()->get();

        $this->assertSame(5, (int) $lines->first()->inherent_likelihood);
        // Still locked, so still untouched — a spreadsheet is a write like any
        // other.
        $this->assertSame(2, (int) $lines->get(1)->inherent_likelihood);
    }

    private function reviewerUser(): \App\Models\User
    {
        return $this->userWith(['rcsa_assessment.view', 'rcsa_assessment.complete']);
    }
}
