import { Head } from '@inertiajs/react';
import AuthenticatedLayout from '@/Layouts/AppLayout';
import KpiCard from '@thirdline/ui/Components/KpiCard';
import PageHeader from '@thirdline/ui/Components/PageHeader';
import { titleCase } from './format';

/**
 * Migration Phase 4.3: risk/loss-events/reports.blade.php.
 *
 * The exports themselves live in ExportController and are untouched. The Blade
 * page loaded EVERY loss event in the tenant to render this screen and used
 * none of the rows; only the count survives.
 */
export default function Reports({ totalEvents = 0, exports: regulatoryExports = [], recentReports = [] }) {
    return (
        <AuthenticatedLayout title="Loss Event Reports">
            <Head title="Loss Event Reports" />

            <PageHeader
                title="Loss Event Reports"
                subtitle="Regulatory returns and management reporting"
                breadcrumbs={[{ label: 'Loss Events', href: route('risk.loss-events.index') }, { label: 'Reports' }]}
            />

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
                <KpiCard title="Events in Register" value={totalEvents} icon="inventory" color="primary" />
                <KpiCard title="Exports Available" value={regulatoryExports.length} icon="download" color="info" />
                <KpiCard title="Recent Generations" value={recentReports.length} icon="history" color="success" />
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mb-6">
                {regulatoryExports.map((entry) => (
                    <div key={entry.url} className="bg-white rounded-xl border border-gray-200 p-5 flex flex-col">
                        <h3 className="text-sm font-semibold text-[#1A365D]">{entry.label}</h3>
                        <p className="text-xs text-gray-500 mt-1 flex-1">{entry.description}</p>
                        {/* Plain anchors: these are file responses, not Inertia
                            visits. */}
                        <a href={entry.url} className="btn-secondary inline-flex items-center gap-2 text-xs mt-4 self-start">
                            <span className="material-symbols-outlined text-base">download</span> Download CSV
                        </a>
                    </div>
                ))}
            </div>

            <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
                <div className="px-5 py-4 border-b border-gray-100">
                    <h3 className="text-sm font-semibold text-[#1A365D]">Recently Generated Reports</h3>
                </div>
                <div className="overflow-x-auto">
                    <table className="data-table">
                        <thead>
                            <tr><th>Report</th><th>Status</th><th>Generated By</th><th>When</th></tr>
                        </thead>
                        <tbody>
                            {recentReports.length === 0 && (
                                <tr><td colSpan={4} className="text-center py-8 text-gray-400">No reports generated yet.</td></tr>
                            )}
                            {recentReports.map((report) => (
                                <tr key={report.id}>
                                    <td className="text-sm font-medium text-[#1A365D]">{report.title ?? '—'}</td>
                                    <td><span className="badge bg-gray-100 text-gray-600">{titleCase(report.status)}</span></td>
                                    <td className="text-xs">{report.generatedBy ?? '—'}</td>
                                    <td className="text-xs text-gray-500">{report.createdAt ?? '—'}</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>
        </AuthenticatedLayout>
    );
}
