<?php

namespace Tests\Unit\Rcsa;

use App\Models\Rcsa\RcsaMethodology;
use App\Services\Rcsa\RcsaCalculationService;
use App\Support\Rcsa\RcsaMethodologyTemplate as Template;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use PHPUnit\Framework\Attributes\Test;
use Symfony\Component\Process\Process;
use Tests\TestCase;

/**
 * The calculation engine against the truth table.
 *
 * resources/js/lib/rcsa-truth-table.json holds all 100 combinations of
 * 5 likelihood × 5 impact × 4 control effectiveness with their expected
 * outputs, written from §3.3 of the implementation plan INDEPENDENTLY of the
 * service. That independence is the point: a fixture generated by the thing
 * under test proves only that the code is deterministic. This one is a second
 * reading of the spec, so the assertion is a disagreement between two readings.
 *
 * The same file is then run through the browser mirror under node, so the two
 * implementations cannot drift. That half skips when node is unavailable —
 * see the note on it.
 */
class RcsaCalculationTest extends TestCase
{
    use RefreshDatabase;

    private RcsaMethodology $methodology;

    protected function setUp(): void
    {
        parent::setUp();

        // The seeded SYSTEM methodology, as the seed migration wrote it. Not a
        // factory: the test is about the client's approved methodology, and a
        // factory would let the fixture and the seed drift apart silently.
        $methodology = RcsaMethodology::withoutGlobalScopes()
            ->whereNull('organization_id')
            ->where('code', Template::CODE)
            ->with(['scaleItems', 'bands'])
            ->first();

        $this->assertNotNull(
            $methodology,
            'The system RCSA methodology is missing. 2026_09_06_100002_seed_rcsa_system_methodology did not run.'
        );

        $this->methodology = $methodology;
    }

    /**
     * @return array<string, mixed>
     */
    private static function truthTable(): array
    {
        $path = base_path('resources/js/lib/rcsa-truth-table.json');

        return json_decode((string) file_get_contents($path), true, 512, JSON_THROW_ON_ERROR);
    }

    /* ------------------------------------------------------------------ */
    /*  The server engine */
    /* ------------------------------------------------------------------ */

    #[Test]
    public function it_matches_the_truth_table_on_all_one_hundred_combinations(): void
    {
        $service = new RcsaCalculationService;
        $table = self::truthTable();

        $this->assertSame(100, count($table['cases']), 'The truth table should hold 5 × 5 × 4 cases.');

        foreach ($table['cases'] as $case) {
            $result = $service->calculate(
                $case['likelihood'],
                $case['impact'],
                $case['controlEffectiveness'],
                $this->methodology,
            );

            $where = sprintf(
                'L%d (%s) × I%d (%s), control %s',
                $case['likelihood'], $case['likelihoodLabel'],
                $case['impact'], $case['impactLabel'],
                $case['controlEffectiveness'],
            );

            $expected = $case['expected'];

            $this->assertSame($expected['inherentScore'], $result->inherentScore, "inherent score: {$where}");
            $this->assertSame($expected['inherentLevel'], $result->inherentLevel, "inherent level: {$where}");
            $this->assertSame($expected['ceModifier'], $result->ceModifier, "CE modifier: {$where}");
            $this->assertSame((float) $expected['residualScore'], $result->residualScore, "residual score: {$where}");
            $this->assertSame($expected['residualLevel'], $result->residualLevel, "residual level: {$where}");
            $this->assertSame($expected['riskTreatment'], $result->riskTreatment, "treatment: {$where}");
            $this->assertSame($expected['appetiteStatus'], $result->appetiteStatus, "appetite: {$where}");
            $this->assertSame($expected['actionPlanRequired'], $result->actionPlanRequired, "action plan: {$where}");
            $this->assertTrue($result->isComplete, "completeness: {$where}");
        }
    }

    /* ------------------------------------------------------------------ */
    /*  Band boundaries */
    /* ------------------------------------------------------------------ */

    /**
     * The cut points, from both sides.
     *
     * A band table is only ever wrong at its edges, and every one of these
     * pairs is a score that changes what the bank must DO about the risk. 4 vs
     * 5 is the difference between accept and mitigate; 9 vs 10 between mitigate
     * and treat.
     *
     * @return array<string, array{float, string}>
     */
    public static function bandBoundaries(): array
    {
        return [
            'below the bottom clamps to very low' => [0.0, 'very_low'],
            'very low tops out at 2' => [2.0, 'very_low'],
            'low starts just above 2' => [2.01, 'low'],
            'a fractional 2.25 is low, not very low' => [2.25, 'low'],
            'low tops out at 4' => [4.0, 'low'],
            'medium starts just above 4' => [4.01, 'medium'],
            'a fractional 4.5 is medium' => [4.5, 'medium'],
            'medium tops out at 9' => [9.0, 'medium'],
            'high starts just above 9' => [9.01, 'high'],
            'a fractional 12.5 is high' => [12.5, 'high'],
            'high tops out at 16' => [16.0, 'high'],
            'very high starts just above 16' => [16.01, 'very_high'],
            'the maximum score is very high' => [25.0, 'very_high'],
            'above the top clamps to very high' => [40.0, 'very_high'],
        ];
    }

    #[Test]
    #[\PHPUnit\Framework\Attributes\DataProvider('bandBoundaries')]
    public function the_bands_cut_where_the_methodology_says_they_cut(float $score, string $expected): void
    {
        $this->assertSame($expected, $this->methodology->bandFor($score)?->level);
    }

    #[Test]
    public function the_bands_are_contiguous_and_span_the_whole_range(): void
    {
        $bands = $this->methodology->bands->sortBy('min_score')->values();

        $this->assertSame(0.0, (float) $bands->first()->min_score, 'The bottom band should start at zero.');
        $this->assertSame(25.0, (float) $bands->last()->max_score, 'The top band should reach the 5 × 5 maximum.');

        // Contiguous to the stored precision. A gap is a score that bands
        // nowhere and renders as a blank badge; an overlap is a score that
        // bands two ways depending on iteration order.
        for ($i = 1; $i < $bands->count(); $i++) {
            $this->assertEqualsWithDelta(
                (float) $bands[$i - 1]->max_score + 0.01,
                (float) $bands[$i]->min_score,
                0.0001,
                "Band {$bands[$i]->level} does not start where {$bands[$i - 1]->level} ends.",
            );
        }
    }

    /* ------------------------------------------------------------------ */
    /*  Defect D2 — residual zero, and the floor that answers it */
    /* ------------------------------------------------------------------ */

    #[Test]
    public function a_fully_achieved_control_drives_residual_to_zero_by_default(): void
    {
        // This is the workbook's behaviour and the plan's defect D2: the worst
        // risk on the register becomes VERY LOW on one control rating. It is
        // pinned here rather than fixed, because §14 Q3 is a decision for the
        // bank and template parity is the default until they take it. If this
        // test ever changes, it should change because someone answered Q3.
        $result = (new RcsaCalculationService)->calculate(5, 5, 'Fully Achieved', $this->methodology);

        $this->assertSame(25, $result->inherentScore);
        $this->assertSame('very_high', $result->inherentLevel);
        $this->assertSame(0.0, $result->residualScore);
        $this->assertSame('very_low', $result->residualLevel);
        $this->assertSame('accept', $result->riskTreatment);
        $this->assertFalse($result->actionPlanRequired);
        $this->assertFalse($result->residualFloored);
    }

    #[Test]
    public function a_residual_floor_lifts_the_score_without_exceeding_the_inherent(): void
    {
        $this->methodology->residual_floor = 5.0;

        $service = new RcsaCalculationService;

        // 25 × 0 = 0, floored to 5, which bands MEDIUM and now demands a plan.
        $high = $service->calculate(5, 5, 'Fully Achieved', $this->methodology);

        $this->assertSame(5.0, $high->residualScore);
        $this->assertSame('medium', $high->residualLevel);
        $this->assertTrue($high->residualFloored);
        $this->assertTrue($high->actionPlanRequired);

        // An inherent 2 must not be floored UP to 5 — a control cannot make a
        // risk worse than it was before the control existed.
        $low = $service->calculate(1, 2, 'Fully Achieved', $this->methodology);

        $this->assertSame(2.0, $low->residualScore);
        $this->assertSame('very_low', $low->residualLevel);
    }

    /* ------------------------------------------------------------------ */
    /*  Partial and invalid input */
    /* ------------------------------------------------------------------ */

    #[Test]
    public function a_partially_scored_line_computes_what_it_can_and_says_it_is_incomplete(): void
    {
        $service = new RcsaCalculationService;

        $noControl = $service->calculate(4, 4, null, $this->methodology);

        // Inherent stands on its own — the assessor has answered J and K.
        $this->assertSame(16, $noControl->inherentScore);
        $this->assertSame('high', $noControl->inherentLevel);

        // Residual does NOT default to the inherent score, and does not default
        // to zero. An unassessed control means an unknown residual, and a zero
        // here would band VERY LOW and report a risk as inside appetite.
        $this->assertNull($noControl->residualScore);
        $this->assertNull($noControl->residualLevel);
        $this->assertNull($noControl->riskTreatment);
        $this->assertNull($noControl->appetiteStatus);
        $this->assertFalse($noControl->actionPlanRequired);
        $this->assertFalse($noControl->isComplete);

        $nothing = $service->calculate(null, null, null, $this->methodology);

        $this->assertNull($nothing->inherentScore);
        $this->assertNull($nothing->residualScore);
        $this->assertFalse($nothing->isComplete);

        $onlyLikelihood = $service->calculate(3, null, 'Fully Achieved', $this->methodology);

        $this->assertNull($onlyLikelihood->inherentScore);
        $this->assertSame(100, $onlyLikelihood->ceModifier, 'A known control rating is still reported.');
        $this->assertNull($onlyLikelihood->residualScore);
    }

    #[Test]
    public function an_out_of_range_rating_is_unassessed_rather_than_clamped(): void
    {
        $service = new RcsaCalculationService;

        // A 7 on a five-point scale is a data error — from a broken import, or
        // a stale value after a methodology change. Clamping it to 5 would put
        // a rating nobody chose into a regulatory return.
        $this->assertNull($service->calculate(7, 3, 'Not Achieved', $this->methodology)->inherentScore);
        $this->assertNull($service->calculate(3, 0, 'Not Achieved', $this->methodology)->inherentScore);
        $this->assertNull($service->calculate(-1, 3, 'Not Achieved', $this->methodology)->inherentScore);
    }

    #[Test]
    public function an_unknown_control_rating_is_not_silently_scored(): void
    {
        $service = new RcsaCalculationService;

        $result = $service->calculate(4, 4, 'Somewhat Achieved', $this->methodology);

        $this->assertNull($result->ceModifier);
        $this->assertNull($result->controlEffectiveness);
        $this->assertNull($result->residualScore);
        $this->assertFalse($result->isComplete);
    }

    #[Test]
    public function control_effectiveness_is_matched_leniently_and_stored_canonically(): void
    {
        $service = new RcsaCalculationService;

        // The label arrives from an uploaded spreadsheet as often as from a
        // select, and casing and stray spaces are not a different rating.
        foreach (['fully achieved', 'FULLY ACHIEVED', '  Fully   Achieved  '] as $spelling) {
            $result = $service->calculate(4, 4, $spelling, $this->methodology);

            $this->assertSame(100, $result->ceModifier, "spelling: {$spelling}");
            $this->assertSame('Fully Achieved', $result->controlEffectiveness, "spelling: {$spelling}");
        }
    }

    /* ------------------------------------------------------------------ */
    /*  Residual modes */
    /* ------------------------------------------------------------------ */

    #[Test]
    public function calculated_mode_ignores_an_assessed_residual_pair(): void
    {
        $result = (new RcsaCalculationService)->calculate(
            5, 5, 'Not Achieved', $this->methodology,
            residualLikelihood: 1, residualImpact: 1,
        );

        // The pair is not a permitted input in this mode, so a stale value left
        // on a line must not quietly become the residual score.
        $this->assertSame(18.75, $result->residualScore);
        $this->assertFalse($result->residualAssessed);
    }

    #[Test]
    public function assessed_mode_takes_the_assessors_pair_and_does_not_floor_it(): void
    {
        $this->methodology->residual_mode = Template::RESIDUAL_ASSESSED;
        $this->methodology->residual_floor = 8.0;

        $service = new RcsaCalculationService;

        $result = $service->calculate(
            5, 5, 'Not Achieved', $this->methodology,
            residualLikelihood: 2, residualImpact: 2,
        );

        $this->assertSame(4.0, $result->residualScore, 'The assessor rated 2 × 2; the floor does not overrule them.');
        $this->assertSame('low', $result->residualLevel);
        $this->assertTrue($result->residualAssessed);
        $this->assertFalse($result->residualFloored);

        // An incomplete pair falls back to the formula rather than to nothing.
        $partial = $service->calculate(
            5, 5, 'Not Achieved', $this->methodology,
            residualLikelihood: 2, residualImpact: null,
        );

        $this->assertSame(18.75, $partial->residualScore);
        $this->assertFalse($partial->residualAssessed);
    }

    /* ------------------------------------------------------------------ */
    /*  Appetite */
    /* ------------------------------------------------------------------ */

    #[Test]
    public function the_seeded_ceiling_agrees_with_every_bands_appetite_sentence(): void
    {
        // Two editable fields say the same thing: `appetite_ceiling_level`
        // decides the obligation, each band's `appetite_status` is the sentence
        // the assessor reads. They must not disagree on the seeded methodology,
        // or the screen would say "Within risk appetite" beside a mandatory
        // action-plan block.
        foreach ($this->methodology->bands as $band) {
            $aboveByCeiling = $this->methodology->isAboveAppetite($band->level);
            $aboveBySentence = str_starts_with($band->appetite_status, Template::ABOVE_APPETITE_PREFIX);

            $this->assertSame(
                $aboveBySentence,
                $aboveByCeiling,
                "Band {$band->level}: the ceiling says ".($aboveByCeiling ? 'above' : 'within')
                    ." appetite but its statement reads \"{$band->appetite_status}\".",
            );
        }
    }

    #[Test]
    public function raising_the_appetite_ceiling_changes_the_obligation(): void
    {
        $service = new RcsaCalculationService;

        // 3 × 3 with a Mostly Achieved control lands at 2.25 — LOW, inside a
        // ceiling of `low`.
        $this->assertFalse($service->calculate(3, 3, 'Mostly Achieved', $this->methodology)->actionPlanRequired);

        // 4 × 4 Partially Achieved lands at 8.00 — MEDIUM, above it.
        $this->assertTrue($service->calculate(4, 4, 'Partially Achieved', $this->methodology)->actionPlanRequired);

        // A bank with a higher tolerance sets the ceiling at MEDIUM, and that
        // same line stops demanding a plan without any band being rewritten.
        $this->methodology->appetite_ceiling_level = 'medium';

        $this->assertFalse($service->calculate(4, 4, 'Partially Achieved', $this->methodology)->actionPlanRequired);
        $this->assertTrue($service->calculate(5, 5, 'Not Achieved', $this->methodology)->actionPlanRequired);
    }

    /* ------------------------------------------------------------------ */
    /*  The seeded methodology */
    /* ------------------------------------------------------------------ */

    #[Test]
    public function the_seed_migration_writes_the_workbook_scales_in_full(): void
    {
        $this->assertSame(5, $this->methodology->scaleItems->where('type', 'likelihood')->count());
        $this->assertSame(5, $this->methodology->scaleItems->where('type', 'impact')->count());
        $this->assertSame(4, $this->methodology->scaleItems->where('type', 'control_effectiveness')->count());
        $this->assertSame(5, $this->methodology->bands->count());

        // Thirty impact criteria: five levels × six dimensions. The plan is
        // explicit that these must be stored and surfaced rather than left in a
        // spreadsheet, and a partially seeded matrix would leave an assessor
        // choosing "High" with no idea what High means outside naira.
        $this->assertSame(
            30,
            DB::table('rcsa_impact_criteria')->where('methodology_id', $this->methodology->id)->count(),
        );

        // The modifiers are the engine. Wrong here, wrong everywhere.
        $modifiers = $this->methodology->scaleItems
            ->where('type', 'control_effectiveness')
            ->pluck('modifier', 'label')
            ->all();

        $this->assertSame([
            'Fully Achieved' => 100,
            'Mostly Achieved' => 75,
            'Partially Achieved' => 50,
            'Not Achieved' => 25,
        ], $modifiers);
    }

    #[Test]
    public function the_system_methodology_is_visible_to_every_tenant(): void
    {
        // organization_id NULL means "system", and the tenancy scope must pass
        // it through — otherwise a fresh tenant resolves no methodology and
        // every RCSA figure in the product is null.
        $resolved = RcsaMethodology::active(organizationId: 999_999);

        $this->assertNotNull($resolved);
        $this->assertSame(Template::CODE, $resolved->code);
    }

    /* ------------------------------------------------------------------ */
    /*  The browser mirror */
    /* ------------------------------------------------------------------ */

    #[Test]
    public function the_browser_mirror_computes_what_the_server_computes(): void
    {
        // There is no JavaScript test runner in this repository, so the mirror
        // is exercised by running it under node from here. This is the only
        // thing standing between resources/js/lib/rcsa-calc.js and silent
        // divergence from the engine — an assessor would see one residual band
        // while typing and a different one after the save landed.
        //
        // Skips rather than fails when node is absent, so that a PHP-only CI
        // image does not report a false red. When it skips, the mirror is
        // unverified; do not read a green suite on such an image as evidence
        // that the two agree.
        $node = trim((string) shell_exec('command -v node 2>/dev/null'));

        if ($node === '') {
            $this->markTestSkipped('node is not available, so the browser mirror cannot be exercised.');
        }

        $runner = base_path('tests/Support/rcsa-calc-runner.mjs');

        $process = new Process(
            [$node, $runner],
            base_path(),
            null,
            json_encode([
                'methodology' => $this->methodology->toCalculatorPayload(),
                'cases' => self::truthTable()['cases'],
            ], JSON_THROW_ON_ERROR),
            60,
        );

        $process->run();

        $this->assertSame(
            0,
            $process->getExitCode(),
            "The browser mirror disagreed with the truth table:\n"
                .$process->getOutput().$process->getErrorOutput(),
        );

        $report = json_decode(trim($process->getOutput()), true, 512, JSON_THROW_ON_ERROR);

        $this->assertSame(100, $report['checked']);
        $this->assertSame([], $report['mismatches']);
    }
}
