<?php

namespace App\Services\Bcms\Reports;

use App\Models\Bcms\AuditLog;
use App\Models\User;
use App\Services\Bcms\Compliance\ClauseComplianceMatrixService;
use App\Support\Bcms\CsatQuestionMap;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Log;
use PhpOffice\PhpSpreadsheet\Cell\Coordinate;
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use ThirdLine\Platform\Tenancy\TenantContext;

/**
 * Fills a CUSTOMER-SUPPLIED CBN CSAT workbook by question label —
 * ADR 0021 §4, phase-11-spec §3.5.
 *
 * NO CELL COORDINATES ARE EVER INVENTED. We do not hold the CSAT workbook, so
 * a coordinate is unknowable, and a guess would put our guess into a bank's
 * regulatory submission — exactly the `NoFabricatedNumbersTest` family with a
 * regulator on the receiving end. The writer finds each question BY LABEL,
 * writes our answer and artefact reference into the adjacent cell, and lists
 * every question it could not find on a cover sheet — never silently.
 *
 * REUSES PhpSpreadsheet, THE PRODUCT'S OWN LIBRARY (RCSA's
 * `RcsaTemplateWriter`/`RcsaWorkbookWriter` are the precedent). `openpyxl` is
 * Python and does not exist in this repository, whatever the blueprint says.
 *
 * NOTHING IS PERSISTED BEYOND THE REQUEST (B9, gate 1 code review #1,
 * compliance-analyst's NDPA register §11 finding). `$path` is the uploaded
 * file's own PHP temp path, cleaned up by PHP at the end of the request; the
 * intermediate `.xlsx` this class writes to disk lives only inside `fill()`'s
 * own `try`/`finally` below, and no row anywhere stores the workbook or its
 * answers — the response streams the bytes back and nothing else keeps them.
 */
class CsatPrefillService
{
    /** @see writeAnswer() */
    private const WRITTEN = 'written';

    private const OCCUPIED = 'occupied';

    private const NOT_FOUND = 'not_found';

    public function __construct(private readonly ClauseComplianceMatrixService $matrix) {}

    /**
     * A9 (gate 1 code review #2): the workbook is a CUSTOMER upload, never
     * generated by this product — `IOFactory::load()` auto-detects the
     * reader by SNIFFING the file's own content, which means a file that is
     * not really an `.xlsx` (a renamed `.xls`, a corrupted upload, or
     * something crafted to be sniffed as a different, less-safe reader)
     * gets handed to whichever reader the sniff picks, not the one this
     * class actually validated the extension against. `createReader('Xlsx')`
     * fixes the reader; a workbook that is not really one throws here,
     * loudly, instead of being parsed by a guess.
     *
     * @return array{bytes: string, matched: int, unmatched: list<string>, occupied: list<string>}
     */
    public function fill(string $path, User $actor): array
    {
        $spreadsheet = IOFactory::createReader('Xlsx')->load($path);
        $built = $this->matrix->build();
        $rows = collect($built['sections'] ?? [])->flatten(1)->keyBy('code');

        $matched = 0;
        $matchedLabels = [];
        $occupied = [];

        foreach (CsatQuestionMap::all() as $mapping) {
            $row = $rows->get($mapping['clause_ref']);

            if ($row === null) {
                continue;
            }

            $answer = $this->answerText($row);
            $outcome = $this->writeAnswer($spreadsheet, $mapping['question_label'], $answer);

            if ($outcome === self::WRITTEN) {
                $matched++;
                $matchedLabels[] = $mapping['question_label'];
            } elseif ($outcome === self::OCCUPIED) {
                $occupied[] = $mapping['question_label'];
            }
        }

        $unmatched = collect(CsatQuestionMap::all())
            ->pluck('question_label')
            ->diff($matchedLabels)
            ->diff($occupied)
            ->values()
            ->all();

        $this->addCoverSheet($spreadsheet, $matched, $unmatched, $occupied);

        $writer = new Xlsx($spreadsheet);
        $tmp = tempnam(sys_get_temp_dir(), 'csat-');

        // B9 (gate 1 code review #1): `$writer->save($tmp)` throwing left a
        // copy of the filled-in (regulator-content-bearing) workbook sitting
        // in the temp directory for ever — `unlink()` never ran. The
        // `finally` runs it regardless of how `fill()` leaves this block.
        try {
            $writer->save($tmp);
            $bytes = (string) file_get_contents($tmp);
        } finally {
            if (is_file($tmp)) {
                unlink($tmp);
            }
        }

        $this->logExport($matched, $unmatched, $occupied, $actor);

        return ['bytes' => $bytes, 'matched' => $matched, 'unmatched' => $unmatched, 'occupied' => $occupied];
    }

    /** @param  array<string, mixed>  $row */
    private function answerText(array $row): string
    {
        return match ($row['state']) {
            'green' => 'Yes — '.$row['artefact'],
            'amber' => 'Partially — '.$row['artefact'],
            'grey' => 'Not applicable — '.$row['artefact'],
            default => 'No — '.$row['artefact'],
        };
    }

    /**
     * B9 (gate 1 code review #1): `for ($col = 'A'; $col <= $highestColumn;
     * $col++)` compared COLUMN LETTERS AS STRINGS, which PHP compares
     * BYTE-BY-BYTE, not the way a spreadsheet reader expects — the first
     * byte where two strings differ decides the whole comparison,
     * regardless of either string's length. Two ways that broke a wide
     * workbook: a target column PAST `Z` (e.g. `AB`) made every one-letter
     * `$col` from `B` onward compare GREATER than `AB` (`'B' > 'A'` at the
     * first byte, and `'AB'` also starts `'A'`), so the loop's own condition
     * went false after column `A` and never scanned the rest of the sheet;
     * conversely a target column of just `Z` let the loop, once it wrapped
     * past `Z` into two-letter columns (`'Z'++` is `'AA'` under PHP's own
     * string increment), keep comparing true (`'AA' < 'Z'` — `'A' < 'Z'` at
     * the first byte) for roughly 676 further iterations, creating cells
     * that were never on the sheet. Looping on the INTEGER column index and
     * converting only at the point of use is what
     * `Coordinate::columnIndexFromString()` exists for.
     *
     * A9 (gate 1 code review #2): the cell ADJACENT to a matched question is
     * no longer overwritten unconditionally — a customer's own workbook may
     * already carry an answer, a note, or simply not have the blank column
     * this class assumes. Landing on an already-occupied cell is reported
     * back as `OCCUPIED`, distinct from `NOT_FOUND`, so the cover sheet can
     * tell a preparer "we found this question but would not overwrite it"
     * rather than the two looking identical.
     *
     * @return 'written'|'occupied'|'not_found'
     */
    private function writeAnswer(Spreadsheet $spreadsheet, string $label, string $answer): string
    {
        foreach ($spreadsheet->getAllSheets() as $sheet) {
            $highestRow = $sheet->getHighestRow();
            $highestColumnIndex = Coordinate::columnIndexFromString($sheet->getHighestColumn());

            for ($row = 1; $row <= $highestRow; $row++) {
                for ($colIndex = 1; $colIndex <= $highestColumnIndex; $colIndex++) {
                    $col = Coordinate::stringFromColumnIndex($colIndex);
                    $value = $sheet->getCell($col.$row)->getValue();

                    if (is_string($value) && trim($value) !== '' && str_contains(strtolower($value), strtolower(substr($label, 0, 40)))) {
                        $nextCol = Coordinate::stringFromColumnIndex($colIndex + 1);
                        $adjacent = $sheet->getCell($nextCol.$row)->getValue();

                        if (is_string($adjacent) && trim($adjacent) !== '') {
                            return self::OCCUPIED;
                        }

                        $sheet->setCellValue($nextCol.$row, $answer);

                        return self::WRITTEN;
                    }
                }
            }
        }

        return self::NOT_FOUND;
    }

    /**
     * A9 (gate 1 code review #2): occupied questions get their OWN labelled
     * block on the cover sheet — "found but not overwritten" is a different
     * fact from "not found at all", and blending the two would leave a
     * preparer unable to tell which rows to check the workbook for
     * themselves.
     *
     * @param  list<string>  $unmatched
     * @param  list<string>  $occupied
     */
    private function addCoverSheet(Spreadsheet $spreadsheet, int $matched, array $unmatched, array $occupied): void
    {
        $cover = $spreadsheet->createSheet(0);
        $cover->setTitle('Pre-fill cover sheet');
        $cover->setCellValue('A1', 'CBN CSAT pre-fill — cover sheet');
        $cover->setCellValue('A2', $matched.' question(s) matched and filled by label.');
        $cover->setCellValue('A3', count($unmatched).' question(s) could not be matched and are listed below, untouched.');
        $cover->setCellValue('A4', count($occupied).' question(s) were found but already had an answer in the adjacent cell, and were left untouched.');

        $row = 6;

        foreach ($unmatched as $label) {
            $cover->setCellValue('A'.$row, $label);
            $row++;
        }

        if ($occupied !== []) {
            $row++;
            $cover->setCellValue('A'.$row, 'Found but not overwritten (an answer was already present):');
            $row++;

            foreach ($occupied as $label) {
                $cover->setCellValue('A'.$row, $label);
                $row++;
            }
        }

        $spreadsheet->setActiveSheetIndex(0);
    }

    /**
     * B9 (gate 1 code review #1): the CSAT pre-fill export had NO
     * `pack.exported` audit row at all — this is the same "generation is
     * recorded" rule §3.1 states for every other pack, with the org node
     * (A2) and a failure counted where `BcmsWatchdog` already looks.
     *
     * @param  list<string>  $unmatched
     * @param  list<string>  $occupied
     */
    private function logExport(int $matched, array $unmatched, array $occupied, User $actor): void
    {
        $organizationId = TenantContext::organizationId();

        try {
            AuditLog::query()->create([
                'organization_id' => $organizationId,
                'auditable_type' => 'bcms_report_pack',
                'auditable_id' => (int) $organizationId,
                'event' => 'pack.exported',
                'after' => [
                    'framework' => 'cbn_csat_prefill',
                    'org_node' => [
                        'organization_id' => $organizationId,
                        'organization_name' => \App\Models\Organization::query()->find($organizationId)?->name,
                    ],
                    'matched' => $matched,
                    'unmatched_count' => count($unmatched),
                    'occupied_count' => count($occupied),
                ],
                'actor_id' => $actor->getKey(),
                'actor_label' => $actor->name,
                'created_at' => now(),
            ]);
        } catch (\Throwable $e) {
            Log::error('BCMS CSAT pre-fill export could not be logged', [
                'exception' => get_class($e),
            ]);

            try {
                Cache::add(AuditLog::AUDIT_FAILURE_CACHE_KEY, 0, now()->addDays(30));
                Cache::increment(AuditLog::AUDIT_FAILURE_CACHE_KEY);
            } catch (\Throwable) {
                // Nothing further to do: the Log::error above is the fallback.
            }
        }
    }
}
