<?php

namespace App\Models\Bcms;

use App\Enums\Bcms\MaturityClauseGroup;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use ThirdLine\Platform\Tenancy\BelongsToOrganization;

/**
 * One clause group's maturity level within an assessment, with the evidence
 * count and the rationale that produced it.
 *
 * The rationale is generated by the engine and stored. A maturity number a
 * customer cannot interrogate is a number they will argue with once and then
 * ignore.
 *
 * @property int $id
 * @property int $organization_id
 * @property int $assessment_id
 * @property \App\Enums\Bcms\MaturityClauseGroup $clause_group
 * @property ?int $score
 * @property int $evidence_count
 * @property int $expected_count
 * @property ?string $rationale
 * @property array<array-key, mixed> $evidence_summary
 * @property ?\Illuminate\Support\Carbon $created_at
 * @property ?\Illuminate\Support\Carbon $updated_at
 */
class MaturityScore extends Model
{
    use BelongsToOrganization, HasFactory;

    protected $table = 'bcms_maturity_scores';

    /** @var list<string> */
    protected $fillable = [
        'organization_id', 'assessment_id', 'clause_group', 'score', 'evidence_count',
        'expected_count', 'rationale', 'evidence_summary',
    ];

    /** @return array<string, string> */
    protected function casts(): array
    {
        return [
            'organization_id' => 'integer',
            'assessment_id' => 'integer',
            'score' => 'integer',
            'evidence_count' => 'integer',
            'expected_count' => 'integer',
            'evidence_summary' => 'array',
            'clause_group' => MaturityClauseGroup::class,
        ];
    }

    /* ------------------------------------------------------------------ */
    /*  Relationships */
    /* ------------------------------------------------------------------ */

    /** @return BelongsTo<MaturityAssessment, $this> */
    public function assessment(): BelongsTo
    {
        return $this->belongsTo(MaturityAssessment::class, 'assessment_id');
    }
}
